version: "3.9"
services:
 jupyter:
  container_name: jupy_container
  image: jupyter/minimal-notebook
  ports: 
    - "4444:8888"
  networks:
    - my_home_network
  environment:
    JUPYTER_TOKEN: "bonjour"
  volumes:
    - .:/home/jovyan/work
 elasticsearch:
  container_name: es_container
  image: elasticsearch:7.2.0
  environment:
    discovery.type: single-node
  ports:
    - "9200:9200"
    - "9300:9300"
  networks:
    - my_home_network
 kibana:
  image: kibana:7.2.0
  container_name: kibana_container
  networks:
  - my_home_network
  ports:
  - "5601:5601"
  depends_on:
  - elasticsearch

networks:
  my_home_network: