version: "3.7"
services:
  web:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "localhost:8080"
    container_name: gitlab-ce
    environment:
      - GITLAB_OMNIBUS_CONFIG=external_url 'http://localhost'
      - GITLAB_USER=root
      - PAT_TOKEN=testtoken2

    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./gitlab/gitlab-runner:/etc/gitlab-runner"
    networks:
      - gitlab
    environment:
      - CI_SERVER_URL=http://gitlab-ce:80
      - PAT_TOKEN=testtoken

networks:
  gitlab:
    name: gitlab-network
